name: branch build

on: 
  push:
    branches:
        - '!main'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6.x' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Run Tests
        run: dotnet test --configuration Release

      - name: Upload E2E failure screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: ./**/e2e*.png
