name: dotnet package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '6.x' ]

    steps:
        - uses: actions/checkout@v2
        - name: Setup dotnet
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.x'
        - name: Install dependencies
          run: dotnet restore
        - name: Build
          run: dotnet build
        - name: Set up Node.js version
          uses: actions/setup-node@v1
          with:
            node-version: '12.x'
        - name: npm install, build
          run: |
            cd App.Server/_Client
            npm install
            npm run build
            mv dist/** ../../wwwroot/**