name: main build and deploy

on: 
  push:
    branches:
      - main

env:
  SERVER: ${{ secrets.FTP_HOST }}
  USER: ${{ secrets.FTP_USER }}
  PASSWORD: ${{ secrets.FTP_PASSWORD }}
  REMOTE_DIRECTORY: ${{ github.event.repository.name }}-${{ github.ref_name }}
  LIB_DIRECTORY : ./.github/workflows
  ARTIFACT_DIRECTORY: ./App.Server/bin/Release/net6.0/publish/

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Host
    strategy:
      matrix:
        dotnet: [ '6.x' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Run Tests
        run: dotnet test --configuration Release

      - name: Upload artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test
          path: |
            ./**/e2e*.png
            ./**/*.log

      - name: Build
        if: github.ref_name == 'main'
        run: dotnet publish --configuration Release

      - name: Deploy FTP
        if: github.ref_name == 'main'
        shell: pwsh
        run: |
          ./.github/workflows/Task/ftp-take-offline.ps1
          ./.github/workflows/Task/ftp-sync.ps1
          ./.github/workflows/Task/ftp-take-online.ps1
