name: build and deploy

on:
  push:
    branches:
      - main

env:
  SERVER: ${{ secrets.FTP_HOST }}
  USER: ${{ secrets.FTP_USER }}
  PASSWORD: ${{ secrets.FTP_PASSWORD }}
  ARTIFACT_DIRECTORY: ./App.Server/bin/Release/net6.0/publish/
  REMOTE_DIRECTORY: rickandmorty-${{ github.ref_name }}
  LIB_DIRECTORY : ./.github/workflows

jobs:
  deployment:

    runs-on: ubuntu-latest
    environment: Host
    strategy:
      matrix:
        dotnet: [ '6.x' ]

    steps:
        - uses: actions/checkout@v2

        - name: Setup dotnet
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '6.x'

        - name: Install dependencies
          run: dotnet restore

        - name: Start Vite
          shell: pwsh
          run: |
            ./dev.cmd

        - name: Run Tests
          run: dotnet test

        - name: Build
          run: dotnet publish --configuration Release

        - name: Take app offline
          shell: pwsh
          run: |
            ./.github/workflows/Task/ftp-take-offline.ps1

        - name: Sync FTP
          shell: pwsh
          run: |
            ./.github/workflows/Task/ftp-sync.ps1

        - name: Take app online
          shell: pwsh
          run: |
            ./.github/workflows/Task/ftp-take-online.ps1
